config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard", as: :dashboard
  get "my_list", to: "pages#my_list", as: :my_list
  post "save_list", to: "pages#save_list", as: :save_list
  delete "destroy_list/:id", to: "pages#destroy_list", as: :destroy_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "shopping_list/:id", to: "ingredients#shopping_list", as: :shopping_list
  get "create_list_ingredients/:id", to: "ingredients#create_list_ingredients", as: :create_list_ingredients
    resources :list_ingredients, only: [:update]
  resources :lists, only: [:create,:update]
  resources :recipes, only: [:index, :show]
  get 'recipes_search', to: 'recipes#search_recipes', as: :search_recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :list_recipes
include PgSearch::Model
  pg_search_scope :search_recipes,
    against: [ :name, :description, :preparation ],
    using: {
      tsearch: { prefix: true }
    }

  def display_ingredients
    recipe_ingredients.map do |ri|
      "#{ri.quantity} #{ri.ingredient.name}"
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    # @array_eric
    # @listeric = Recipe.all.each do |recipe|
    #   @array_eric << recipe.ingredients
    # end
  end

  def search_recipes
    if params[:query].present?
      @recipes = Recipe.search_recipes(params[:query])
    else
      render :index
    end
end

end

app/views/recipes/_recipe_cards.html.erb
<div class="card-index-wow">
  <div class="super-image-de-gros-mangeur" style="background-image: url('<%= image_path(recipe.picture) %>')">
  </div>
    <div class="title-rating-bonheur">
      <h5><%= recipe.name %></h5>

      <% recipe.rating.to_i.times do  %>
          <i class="fas fa-heart"></i>
      <% end %>

      <div class="sans-nom">
        <%= link_to  "Détails", recipe_path(recipe), class: "mouloude" %>
      </div>

  </div>
</div>

app/views/recipes/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

<div class="searchbarcool">
  <%= form_tag search_recipes_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query], placeholder: 'Rechercher une recette',
    class: "form-control form-control-lg form-control-borderless" %>
  <%= submit_tag "Rechercher", class: "btn btn-lg btn-succes" %>
  <% end %>
</div>

<div class="center-parc">
  <% @recipes.each do |recipe| %>
    <%= render "recipe_cards", recipe: recipe %>
  <% end %>
</div>

app/views/recipes/search_recipes.html.erb
<% @recipes.each do |recipe| %>
<%= render "recipe_cards", recipe: recipe %>
<% end %>

app/views/recipes/show.html.erb
<div class="card-show">
   <div class="header">
    <%= image_tag(@recipe.picture) %>
      <div class="icon">
      </div>
   </div>
   <div class="text">
      <h1 class="food">
         <%= @recipe.name %>
      </h1>
         <i class="fa fa-clock-o"> <%= @recipe.cooking_time %></i>
      <div class="stars">
         <% @recipe.rating.to_i.times do  %>
            <i class="fas fa-heart"></i>
         <% end %>
      </div>
      <p><strong>Description:</strong></p>
        <p style="white-space: pre-line;"><%= @recipe.description %></p>
        <br>
      <p class="info"><strong>Ingredient:</strong>
      <br>
      <br>
        <% @recipe.ingredients.each do |i| %>
            <%= i.name %>,
        <% end %></p>
   </div>
      <%= link_to  "Retour", recipes_path(@recipe), class: "btn" %>
    </div>