config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard", as: :dashboard
  get "my_list", to: "pages#my_list", as: :my_list
  post "save_list", to: "pages#save_list", as: :save_list
  delete "destroy_list/:id", to: "pages#destroy_list", as: :destroy_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "shopping_list/:id", to: "ingredients#shopping_list", as: :shopping_list
  get "create_list_ingredients/:id", to: "ingredients#create_list_ingredients", as: :create_list_ingredients
    resources :list_ingredients, only: [:update]
  resources :lists, only: [:create,:update]
  resources :recipes, only: [:index, :show]
  get 'recipes_search', to: 'recipes#search_recipes', as: :search_recipes
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :list_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def shopping_list
    # @recipes = current_user.lists.last.recipes
    # @ingredients = []
    # @recipes.each do |recipe|
    #   @ingredients << recipe.recipe_ingredients
    # end
    # @recipes = Recipe.where(user: current_user)
    # @list = current_user.lists.last
    @list = List.find(params[:id])
    @quantity_ingredients = session[:data]
    # @list_ingredients = @list.list_ingredients
  end
  def create_list_ingredients
    @list = List.find(params[:id])
    @recipes = @list.recipes
    @recipe_ingredients = @recipes.map {|recipe| recipe.recipe_ingredients}.flatten
    quantity_ingredients = {}
    @recipe_ingredients.each do |recipe_ingredient|
      unless quantity_ingredients.key?(recipe_ingredient.ingredient.name)
        quantity_ingredients[recipe_ingredient.ingredient.name] = [0, nil]
      end
      if ['g', 'gr'].include?(recipe_ingredient.unit)
        unit = 'kg'
        quantity = (recipe_ingredient.quantity.to_i / 1000) + 1
      elsif recipe_ingredient.unit == 'cl'
        unit = 'l'
        quantity = (recipe_ingredient.quantity.to_i / 1000) + 1
      else
        unit = recipe_ingredient.unit
        quantity = recipe_ingredient.quantity.to_i
      end
      quantity_ingredients[recipe_ingredient.ingredient.name][1] = unit
      quantity_ingredients[recipe_ingredient.ingredient.name][0] += quantity
    end

    # @ingredients = @recipes.map {|recipe| recipe.ingredients}.flatten
    @list_ingredients = []
    quantity_ingredients.each do |name, quantity_unit|
      list_ingredient = ListIngredient.create(list: @list, ingredient: Ingredient.find_by(name: name), checked: false)
      @list_ingredients << list_ingredient
    end
    session[:data] = quantity_ingredients
    redirect_to shopping_list_path(@list)
  end
end

app/views/ingredients/shopping_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card card-white">
        <div class="card-body">
          <ul class="nav nav-pills todo-nav">
            <h1>Liste de courses</h1>
          </ul>
          <div class="todo-list">
            <% @quantity_ingredients.each do |name, quantity_unit| %>
              <% ingredient = Ingredient.find_by(name: name) %>
              <% list_ingredient = ListIngredient.find_by(ingredient: ingredient, list: @list) %>
              <div class="todo-item" data-id="<%= list_ingredient.id %>">
   <%= simple_form_for(list_ingredient, method: :patch, url: list_ingredient_path(list_ingredient)) do |f| %>
    <%= f.input :checked,
    label: "#{ingredient.name} #{quantity_unit[0] == 0 ? '' : quantity_unit[0] } #{quantity_unit[1]}",
    input_html: { class: 'ingredient-input checker', autocomplete: "checked" },
    label_html: { class: 'ingredient-label'}  %>
    <%= f.button :submit, 'boutton', class: "d-none ingredient-button" %>
  <% end %>
</div>
<% end %>
<%= link_to "Fini", my_list_path, class: "btn btn-success", id: "list-finish" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>