config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard", as: :dashboard
  get "my_list", to: "pages#my_list", as: :my_list
  post "save_list", to: "pages#save_list", as: :save_list
  delete "destroy_list/:id", to: "pages#destroy_list", as: :destroy_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "shopping_list/:id", to: "ingredients#shopping_list", as: :shopping_list
  get "create_list_ingredients/:id", to: "ingredients#create_list_ingredients", as: :create_list_ingredients
    resources :list_ingredients, only: [:update]
  resources :lists, only: [:create,:update]
  resources :recipes, only: [:index, :show]
  get 'recipes_search', to: 'recipes#search_recipes', as: :search_recipes
end

app/views/pages/dashboard.html.erb
<div class="container">
<h1 class="title-bangers">MES LISTES</h1>
</div>

<div class="container">
  <div class="row">
    <div class="column">
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures[0]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[0]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[1]) %>
        <p class="ml-2 mb-0">LUN</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures[1]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[2]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[3]) %>
        <p class="ml-2 mb-0">MAR</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures[2]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[4]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[5]) %>
        <p class="ml-2 mb-0">MER</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures[3]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[6]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[7]) %>
        <p class="ml-2 mb-0">JEU</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures[4]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[8]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[9]) %>
        <p class="ml-2 mb-0">VEN</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures[5]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[10]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[11]) %>
        <p class="ml-2 mb-0">SAM</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures[6]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[12]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures[13]) %>
        <p class="ml-2 mb-0">DIM</p>
      </div>
      <div class="d-flex justify-content-between mt-3 align-items-center">
        <p class="price my-0">PRIX: <%= @sorted_recipes[@i-1][1]/100.to_f %><%= "€" %></p>
        <div class="btns-dashboard"><p class="mb-0"><%= link_to "Sélectionner",save_list_path(recipes: @sorted_recipes[@i-1][0]), method: :post  %></p></div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="container">
  <div class="row">
    <div class="column">
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures1[0]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[0]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[1]) %>
        <p class="ml-2 mb-0">LUN</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures1[1]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[2]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[3]) %>
        <p class="ml-2 mb-0">MAR</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures1[2]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[4]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[5]) %>
        <p class="ml-2 mb-0">MER</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures1[3]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[6]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[7]) %>
        <p class="ml-2 mb-0">JEU</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures1[4]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[8]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[9]) %>
        <p class="ml-2 mb-0">VEN</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures1[5]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[10]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[11]) %>
        <p class="ml-2 mb-0">SAM</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures1[6]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[12]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures1[13]) %>
        <p class="ml-2 mb-0">DIM</p>
      </div>
      <div class="d-flex justify-content-between mt-3 align-items-center">
        <p class="price my-0">PRIX: <%= @sorted_recipes[@i-2][1]/100.to_f %><%= "€" %></p>
        <div class="btns-dashboard"><p class="mb-0"><%= link_to "Sélectionner",save_list_path(recipes: @sorted_recipes[@i-2][0]), method: :post  %></p></div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="container">
  <div class="row">
    <div class="column">
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures2[0]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[0]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[1]) %>
        <p class="ml-2 mb-0">LUN</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures2[1]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[2]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[3]) %>
        <p class="ml-2 mb-0">MAR</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures2[2]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[4]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[5]) %>
        <p class="ml-2 mb-0">MER</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures2[3]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[6]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[7]) %>
        <p class="ml-2 mb-0">JEU</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures2[4]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[8]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[9]) %>
        <p class="ml-2 mb-0">VEN</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures2[5]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[10]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[11]) %>
        <p class="ml-2 mb-0">SAM</p>
      </div>
      <div class="day d-flex align-items-center" >
        <%=image_tag(@breakfast_pictures2[6]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[12]) %>
        <p class="mx-2 mb-0">+</p>
        <%=image_tag(@pictures2[13]) %>
        <p class="ml-2 mb-0">DIM</p>
      </div>
      <div class="d-flex justify-content-between mt-3 align-items-center">
        <p class="price my-0">PRIX: <%= @sorted_recipes[@i-3][1]/100.to_f %><%= "€" %></p>
        <div class="btns-dashboard"><p class="mb-0"><%= link_to "Sélectionner",save_list_path(recipes: @sorted_recipes[@i-3][0]), method: :post  %></p></div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <p class="budget">Budget / semaine</p>
  <form action="dashboard" method="get">
  <label for="range">
    <input type="range" name="budget" id="range" min="70" max="100" step="5" value="175"/>
  </label>
    <div class="home-button">
      <input type="submit" value="C'est parti !">
    </div>
  </form>
  <output for="range" class="output"></output>
<div class="row pop-up">
  <div class="box small-6 large-centered">
    <a href="#" class="close-button">&#10006;</a>
    <h3>Bonjour !</h3>
    <div class="poptext">
      <p>Bienvenue dans Foodent, l'application alimentaire pour les étudiants</p>
      <p>Le concept est simple, vous saisissez votre budget alimentaire pour la semaine et l'appli vous proposera plusieurs listes de repas complets pour une période de 7 jours</p>
      <p>Si vous aimez une liste, inscrivez-vous simplement pour l'ajouter à votre profil</p>
    </div>
  </div>
</div>
</div>

app/views/pages/my_list.html.erb
<div class="centreuse-jean-loup">
  <div class="container-list">
    <h4>Lundi</h4>
      <div class="dayli-list">
        <div class="image"><%=image_tag(@chosen_breakfast[0])%><p><%= link_to @recipe_names[14], recipe_path(Recipe.find_by(name: @recipe_names[14])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[0]) %><p><%= link_to @recipe_names[0], recipe_path(Recipe.find_by(name: @recipe_names[0])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[1]) %><p><%= link_to @recipe_names[1], recipe_path(Recipe.find_by(name: @recipe_names[1])) %></p></div>
      </div>
    <h4>Mardi</h4>
      <div class="dayli-list">
        <div class="image"><%=image_tag(@chosen_breakfast[1]) %><p><%= link_to @recipe_names[15], recipe_path(Recipe.find_by(name: @recipe_names[15])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[2]) %><p><%= link_to @recipe_names[2], recipe_path(Recipe.find_by(name: @recipe_names[2])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[3]) %><p><%= link_to @recipe_names[3], recipe_path(Recipe.find_by(name: @recipe_names[3])) %></p></div>
      </div>
    <h4>Mercredi</h4>
      <div class="dayli-list">
        <div class="image"><%=image_tag(@chosen_breakfast[2]) %><p><%= link_to @recipe_names[16], recipe_path(Recipe.find_by(name: @recipe_names[16])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[4]) %><p><%= link_to @recipe_names[4], recipe_path(Recipe.find_by(name: @recipe_names[4])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[5]) %><p><%= link_to @recipe_names[5], recipe_path(Recipe.find_by(name: @recipe_names[5])) %></p></div>
      </div>
    <h4>Jeudi</h4>
      <div class="dayli-list">
        <div class="image"><%=image_tag(@chosen_breakfast[3]) %><p><%= link_to @recipe_names[17], recipe_path(Recipe.find_by(name: @recipe_names[17])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[6]) %><p><%= link_to @recipe_names[6], recipe_path(Recipe.find_by(name: @recipe_names[6])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[7]) %><p><%= link_to @recipe_names[7], recipe_path(Recipe.find_by(name: @recipe_names[7])) %></p></div>
      </div>
    <h4>Vendredi</h4>
      <div class="dayli-list">
        <div class="image"><%=image_tag(@chosen_breakfast[4]) %><p><%= link_to @recipe_names[18], recipe_path(Recipe.find_by(name: @recipe_names[18])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[8]) %><p><%= link_to @recipe_names[8], recipe_path(Recipe.find_by(name: @recipe_names[8])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[9]) %><p><%= link_to @recipe_names[9], recipe_path(Recipe.find_by(name: @recipe_names[9])) %></p></div>
      </div>
    <h4>Samedi</h4>
      <div class="dayli-list">
        <div class="image"><%=image_tag(@chosen_breakfast[5]) %><p><%= link_to @recipe_names[19], recipe_path(Recipe.find_by(name: @recipe_names[19])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[10]) %><p><%= link_to @recipe_names[10], recipe_path(Recipe.find_by(name: @recipe_names[10])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[11]) %><p><%= link_to @recipe_names[11], recipe_path(Recipe.find_by(name: @recipe_names[11])) %></p></div>
      </div>
    <h4>Dimanche</h4>
      <div class="dayli-list">
        <div class="image"><%=image_tag(@chosen_breakfast[6]) %><p><%= link_to @recipe_names[20], recipe_path(Recipe.find_by(name: @recipe_names[20])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[12]) %><p><%= link_to @recipe_names[12], recipe_path(Recipe.find_by(name: @recipe_names[12])) %></p></div>
        <div class="image"><%=image_tag(@chosen_pictures[13]) %><p><%= link_to @recipe_names[13], recipe_path(Recipe.find_by(name: @recipe_names[13])) %></p></div>
      </div>
      <div class="d-flex justify-content-between mt-3 align-items-center">
        <p class="price my-0">PRIX: <%= @chosen_counter/100.to_f %><%= "€" %></p>
        <% if @list_waiting.present? %>
        <%= link_to "Voir ma liste de course", shopping_list_path(current_user.lists.last) %>
        <% else %>
         <%= link_to "Générer ma liste de course", create_list_ingredients_path(@chosen_list) %>
        <% end %>
</div>